### ISSUE TITLE
create automation that adds new website team members to github repos

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tables#42]
### Overview
We need to add people from the Website onboard form to the read and write GitHub teams so that the process can be automated for the website team member who is running the dev room 1 during onboarding nights.

### Action Items
- [x] Bonnie creates email address for this limited use
- [x] create github account for the user
   - [x] log in as hackforla-onboarding github user and add this user to the github teams
   - [x] upgrade the permissions for this new user to a maintainer of teams.
- [x] review existing scripts that do adding in tables
- [x] write script and test
- [x] add info to wiki (the page will be created by Justin and will be called website.md)

### Resources/Instructions
- hfla-website-checklist@hackforla.org
- [Guide: How to Set Up 2FA in GitHub Using 1Password](https://docs.google.com/document/d/1OA7Pf-Yv7-sNsb6Aw6UU8iFs6MSacM55GvFtl_OWm80/edit?usp=share_link)
- [Website onboarding form](https://tables.area120.google.com/u/0/form/80QWxNLn_ehajAGpCcx4Ej/t/9zbNZkfHUltaJ3isu4c4ywbrD_O8ucFn5cUruf1Mf_at8ZmOdy7ADrF1xnRNF6p4O0)
- https://github.com/hackforla/tables/blob/main/dev-docs/app-scripts.md
- https://github.com/hackforla/tables/blob/main/dev-docs/tables.md

#### GitHub teams
- https://github.com/orgs/hackforla/teams/website-write
- https://github.com/orgs/hackforla/teams/website

**Comment by ExperimentsInHonesty** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by hkatzdev** [comment]
I have completed all tasks and finished implementing this. I tested my script on the test table and it successfully ran, so I have moved it to production.

Tables passes the script the invitee's username, their role, and the teams they are joining. This makes it easy to reuse for additional teams. Right now, the Github token and the organization name are stored as "environment variables" (which are simulated by properties). It is possible to pass the Github token in from Tables, but I don't believe it is a good idea to store secrets on Tables itself.

An interesting thing to note is that the form _can not_ add someone who is not in the organization to the team. However, since anyone who is signing up for the website team should already be in the org, this is a non-issue.

The token is a classic token. Classic tokens are considered legacy, but the new fine-tunes tokens have expiration dates. It would be a good idea to look into Github apps in the future in case Classic tokens get fully deprecated. I doubt they will be removed anytime soon - they are used for too many things. However, it is possible that Github may follow in Slack's steps and prevent creation of new tokens in the future.

When attempting to test, I noticed that tables2@hackforla.org is not a valid email - not 100% sure why that is in the 1password. Additionally, I had to configure 2 factor authentication on tablesuser01@gmail.com for both Google and Github to successfully test my script.

Github's error codes and token scopes don't have the best documentation, so here is the result of my experiments.

At first, I tried a classic token with read and write perms. As you can see below, this scope claims to be able to modify team membership.
![Write perms](https://github.com/hackforla/tables/assets/44281159/5a101a3a-e4b6-4f31-a727-38196e384e6f)
However, I kept receiving the following 403 error whenever I tried to use the token.
![403 error](https://github.com/hackforla/tables/assets/44281159/88b02a33-837a-4c74-9a63-34dbc92d05b5)
This error message is incorrect however - if you use a token with only write:org and read:org permissions, you will always receive that error regardless if you are an owner, team maintainer, or just a random person.
Github's team documentation lists what error codes mean, but it is not an exhaustive list - it makes it seem like every code only has one purpose when this is not the case.
![Team specific error codes](https://github.com/hackforla/tables/assets/44281159/d8f52a1d-f713-4750-b0ac-3069272940c3)
If you search in the more general documentation, you will find this explanation which is much more helpful.
![General 403 error code](https://github.com/hackforla/tables/assets/44281159/1361a9ca-285b-46ac-ab3d-5f2a41930b46)
For whatever reason, Github requires that your token has the admin:org scope. Once I added this scope I could add members who were in the organization to the website and website-write team.

Interestingly, trying to add someone who is not in the organization to a team gives a bizarre error code - which I expected it to error, I assumed that it would give the same 403 error as before. Instead, it gave this: 
![422 error](https://github.com/hackforla/tables/assets/44281159/cc302c66-218f-4077-8c04-7234ed36760b)
Why a 422 error? Absolutely no clue. No where in the documentation does it mention how insufficient permissions would result in a 422 error code. However, it does make it easy to tell apart the token not having the required scopes and the user not having the required permissions at least.

TL'DR of the Github specific stuff:
If you are trying to add a user to a team and are getting a 403 error code, your token needs the admin:org scope. If you are getting a 422 error code, you are trying to add someone from outside the organization and you are not an owner.
